### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/boxoffice#98]
A campaign is essentially a marketing activity carried out on a specific channel (twitter or facebook) to increase registrations. Making campaigns and tracking them against orders helps an event admin ascertain the effectiveness of their marketing strategies.

The campaign model can start simple i.e it can start with an `organization_id` and a `referrer_code` (a buid or a custom string). An `order` can store the `campaign_id`, thus helping track the orders against a campaign.

Related:
https://github.com/hasgeek/boxoffice/issues/73

**Comment by jace** [comment]
What happens when you see a new `utm_*` header in an order? Do you automatically make a new `Campaign` record for it? What about a campaign that got a page load but no further interaction? Do you want to ignore those or record them too? This opens up the possibility of a DoS attack flooding our db with fake campaigns.

I'd record `utm_*` headers in the order (or in an `EventSession` like in Hasjob), without bothering to identify the actual campaign. In the dashboard, we list all unique `utm_*` tags and let the user explicitly identify the campaign by creating a `Campaign` record.

**Comment by shreyas-satish** [comment]
> Do you automatically make a new Campaign record for it?

No, a campaign is only created by an admin. When a purchase order is created, the system checks if the URL has a `campaign` parameter and if it does, the `campaign_id` of the appropriate campaign is stored in the `order`.

The reason I don't want to use the `utm_campaign` header is because other clients (like mailchimp) might add their `utm` headers. Having a separate `campaign` header makes this separation clear and explicit.

**Comment by jace** [comment]
Don't make new kinds of campaign headers. `utm_campaign` is perfectly good enough.

**Comment by shreyas-satish** [comment]
Implemented in https://github.com/hasgeek/boxoffice/pull/100
